language: go

jobs:
    include:
        - os: linux
          dist: bionic
          go: 1.13.x

        - os: linux
          dist: trusty
          go: 1.13.x

        - os: osx
          go: 1.13.x

install: true

script:
  - make tests

