# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go



stages:
 - stage: tests
   displayName: 'Tests'
   jobs:
   - job: Ubuntu_16_04_Go_1_11
     displayName: 'Unit tests (Ubuntu 16.04, Go 1.11)'
     pool:
       vmImage: 'ubuntu-16.04'
     variables:
       GOBIN:  '$(GOPATH)/bin' # Go binaries path
       GOROOT: '/usr/local/go1.11' # Go installation path
       GOPATH: '$(system.defaultWorkingDirectory)/gopath' # Go workspace path
       modulePath: '$(GOPATH)/src/github.com/$(build.repository.name)' # Path to the module's code
       GO111MODULE: 'on'
     steps:
     - script: |
         mkdir -p '$(GOBIN)'
         mkdir -p '$(GOPATH)/pkg'
         mkdir -p '$(modulePath)'
         shopt -s extglob
         shopt -s dotglob
         mv !(gopath) '$(modulePath)'
         echo '##vso[task.prependpath]$(GOBIN)'
         echo '##vso[task.prependpath]$(GOROOT)/bin'
       displayName: 'Set up the Go workspace'

     - script: go run ./cmd/make test
       workingDirectory: '$(modulePath)'
       displayName: 'Run unit tests'

   - job: Ubuntu_18_04_Go_1_12
     displayName: 'Unit tests (Ubuntu 18.04, Go 1.12)'
     pool:
       vmImage: 'ubuntu-18.04'
     variables:
       GOBIN:  '$(GOPATH)/bin' # Go binaries path
       GOROOT: '/usr/local/go1.12' # Go installation path
       GOPATH: '$(system.defaultWorkingDirectory)/gopath' # Go workspace path
       modulePath: '$(GOPATH)/src/github.com/$(build.repository.name)' # Path to the module's code
     steps:
     - script: |
         mkdir -p '$(GOBIN)'
         mkdir -p '$(GOPATH)/pkg'
         mkdir -p '$(modulePath)'
         shopt -s extglob
         shopt -s dotglob
         mv !(gopath) '$(modulePath)'
         echo '##vso[task.prependpath]$(GOBIN)'
         echo '##vso[task.prependpath]$(GOROOT)/bin'
       displayName: 'Set up the Go workspace'

     - script: go run ./cmd/make test
       workingDirectory: '$(modulePath)'
       displayName: 'Run unit tests'


   - job: Ubuntu_18_04_Go_1_13
     displayName: 'Unit tests (Ubuntu 18.04, Go 1.13)'
     pool:
       vmImage: 'ubuntu-18.04'
     variables:
       GOBIN:  '$(GOPATH)/bin' # Go binaries path
       GOROOT: '/usr/local/go1.13' # Go installation path
       GOPATH: '$(system.defaultWorkingDirectory)/gopath' # Go workspace path
       modulePath: '$(GOPATH)/src/github.com/$(build.repository.name)' # Path to the module's code
     steps:
     - script: |
         mkdir -p '$(GOBIN)'
         mkdir -p '$(GOPATH)/pkg'
         mkdir -p '$(modulePath)'
         shopt -s extglob
         shopt -s dotglob
         mv !(gopath) '$(modulePath)'
         echo '##vso[task.prependpath]$(GOBIN)'
         echo '##vso[task.prependpath]$(GOROOT)/bin'
       displayName: 'Set up the Go workspace'

     - script: go run ./cmd/make test
       workingDirectory: '$(modulePath)'
       displayName: 'Run unit tests'

